config/routes.rb
Trivialy::Application.routes.draw do

  root 'welcome#index'

  resources :users do
    resources :games do
      resources :questions do
    end
  end
end

  #/users/1
  # START A NEW GAME

  #/games/1/questions/1
  # Random question from the questions table

  # Answer input
  # SUBMIT

  #/games/1/questions/2


  resource :session, only: [:new, :create, :destroy]



end

###################### EXAMPLE #####################
# http://stackoverflow.com/questions/7164865/how-to-populate-fields-in-a-has-many-through-join-table
#The you can use things like form_for(@physician, @patient)
#and url's like physician/1/patient/23
#for updating a patient within the context of a physician.
#######################################################

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :users
  has_and_belongs_to_many :questions

  def next_question
    if questions.none?
      return Question.order("RANDOM()").first
    elsif questions.count <= 4
      Question.where("id not in (?)", self.questions.pluck(:id)).order("RANDOM()").first
    else
      false
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_and_belongs_to_many :games

  def correct_answer?(user_answer)
    answer.downcase == user_answer.downcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true

  has_secure_password

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :current_user, only: [:edit]
  # def new
  # end

  def create
    @game = Game.new(score: 0)
    @game.save!

    @user = User.find( params[:user_id] )
    @user.games << @game

    @game.reload

    #binding.pry

    redirect_to edit_user_game_path( @user, @game )
  end

  def update
    answered_question = Question.find(params[:question_id])
    @game = Game.find(params[:id])
    @game.questions << answered_question

    if answered_question.correct_answer?(params[:your_answer_is])
      # Increment the score
      s = rand(5..50)
      @game.score += s
    end

    # Move on to the next question

    @game.save

    if @question = @game.next_question
      render :edit
    else
      #binding.pry
      render :over
    end

  end

  def edit
    @game = Game.find(params[:id])
    @question = @game.next_question
  end

  # def show

  # end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # once the game size is defined I need to iterate through that many questions

  def show
    @question = Question.find(params[:id])
  end

  # if the answer equals the correct answer set score to 10, if incorrect = 0
  def score
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @game = Game.all.order("score DESC")
    @user = User.all
    render :new
  end

  def create
    # authenticate that user/pass combo is legit
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to user_path(user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    # I will need to define this path
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticated!, :set_user, :authorized!, except: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

## Moved to the SessionsHelper
  # def logged_in?
  #   session[:user_id].present?
  # end

  # def authenticated!
  #   unless logged_in?
  #     redirect_to new_session_path
  #   end
  # end

  def set_user
    @user = User.find(params[:id])
  end

  def authorized!
    unless @user.id == session[:user_id]
      redirect_to user_path(session[:user_id])
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def authenticated!
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/edit.html.erb
<h1> Commuter Trivialy!</h1>


<h3>Category: <%= @question.category.capitalize %></h3>
<div class="question">
  <p>Question: <%= @question.question %><p>
</div>

<%= form_tag user_game_path(current_user, @game), :action => :update, :method => :put do %>
<%= hidden_field_tag :question_id, @question.id %>
<div class="answer">
  <%= label_tag :your_answer_is  %>
  <%= text_field_tag :your_answer_is %>
</div>
<div class="button">
<%= submit_tag "Check Answer" %>
</div>
<% end %>

<p>Score: <%= @game.score %></p>

app/views/games/over.html.erb
<h1>Game Over</h1>

<h2>Your Final Score is: <%= @game.score %></h2>



<% if logged_in? %>
  <%= link_to "Play Again", user_games_path(current_user), :method => :post %>
<% end %>

<table class="center">
  <tr>
    <th scope="col">Correct Answers</th>
  </tr>
  <% @game.questions.each do |q| %>
  <tr>
    <td><%= q.answer %></td>
  </tr>
  <% end %>
</table>

app/views/games/update.html.erb
<h1>Games/Update</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trivialy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
 <nav>
    <% if logged_in? %>
        <%= link_to 'Logout', session_path, :method => :delete %>
    <% end %>
  </nav>
</body>
</html>

app/views/questions/show.html.erb
<h1> Question/Show </h1>

<h3>Category: <%= @question.category.capitalize %></h3><br>
<p>Question: <%= @question.question %><p><br>


<!-- I need a form to grab the user answer and compare to the actual anwser -->

<!-- I also want to display the score -->

<!-- form_for [@game @question] do |f| -->
<!--      f.label :Your Answer -->
<!--      f.text_field : -->


<!--      f.label :answer (originally hidden) -->
<!--      f.label :submit -->
<!-- end -->

app/views/users/_form.html.erb
<% unless @user.errors.none? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<div class="session_start">
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>
</div>

<img src="http://www.mikeolbinski.com/theblog/wp-content/uploads/2010/09/2010-09-28-SunsetTracks_MG_5903_4_5_6_7_8.jpg"
class="medium" />

app/views/users/edit.html.erb
<h1>Editing <%= @user.email %></h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Welcome to Commuter Trivialy!</h1>

<div class="session_start">
<h4>Please sign in to play!</h4>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome:  <%= @user.email %></h1>


<% if logged_in? %>
  <div class="session_start">
    <%= button_to "Play Trivia", user_games_path(@user), :method => :post %>
  </div>
<% end %>

<div class="session_start">
  <%= button_to "Edit User", edit_user_path(@user), :method => :get %><br>
</div class="button">



<table class="center">
  <tr>
    <th scope="col" colspan="2">Your Scores!</th>
  </tr>
   <tr>
      <th scope="col">Game #</th>
      <th scope="col">Score</th>
    </tr>
  <% @user.games.each do |game| %>
    <tr>
      <td><%= game.id %></td>
      <td><%= game.score %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h1>Welcome to Commuter Trivialy!</h1>
  <ul>
    Instructions:
      <li>A game consits of 5 general knowledge questions</li>
      <li>For each correct response you will be awarded a score between 5 and 25 pts</li>
      <li>For questions with multi-part answers use this format: answer / answer / answer</li>
      <li>The case of the response doesn't matter, but spelling does!</li>
  </ul>

<div class="session_start">
  <div class="button_box">
    <%= button_to "Sign Up!", new_user_path(@user), :method => :get %>
  </div>

  <div class="button_box">
    <%= button_to "Sign In!", new_session_path(@user), :method => :get %>
  </div>
</div>


<img src="http://www.michellesarabia.com/wp-content/uploads/2013/07/traintracks.jpg"
class="medium" />